// packages/huginn-website/src/Download.vue
<script setup lang="ts">
import type { APIGetAllReleasesResult, APIGetLatestReleaseResult } from "@huginn/shared";
import { onMounted, ref } from "vue";
import VersionCard from "./components/VersionCard.vue";

export type FlavourType = "nightly" | "release";
const latestRelease = ref<APIGetLatestReleaseResult>(undefined);
const allReleases = ref<APIGetAllReleasesResult>([]);
const loading = ref(false);
const loading2 = ref(false);
const showingOlder = ref(false);

onMounted(async () => {
   loading.value = true;
   const url = new URL("/api/latest-release", import.meta.env.VITE_SERVER_ADDRESS).toString();
   latestRelease.value = await (await fetch(url)).json();
   loading.value = false;
})

async function loadOrHideOlder() {
   if (showingOlder.value) {
      allReleases.value = [];
      showingOlder.value = false;
      return;
   }

   loading2.value = true;

   const url = new URL("/api/all-releases", import.meta.env.VITE_SERVER_ADDRESS).toString();
   allReleases.value = (await (await fetch(url)).json() as APIGetAllReleasesResult).filter(x => x.version !== latestRelease.value?.version);

   loading2.value = false;
   showingOlder.value = true;
}
</script>

<template>
   <div class="flex flex-col mt-32 md:mt-52 w-full">
      <div class="flex flex-col mb-10">
         <div class="text-5xl font-extrabold text-center w-full">Download Huginn</div>
         <div class="text-xl mt-7 text-center w-full">Please choose your version</div>
      </div>

   </div>
   <div class="flex flex-col gap-y-5 items-center px-4 mb-auto pb-32">
      <div v-if="loading" class="text-xl font-bold animate-pulse">Loading...</div>

      <VersionCard v-if="latestRelease" :version="latestRelease.version" :date="latestRelease.date" latest
         :url="latestRelease.url" :windows-setup-url="latestRelease.windowsSetupUrl"
         :macos-setup-url="latestRelease.macosSetupUrl" :linux-setup-url="latestRelease.linuxSetupUrl" />

      <button class="hover:underline text-accent text-lg" @click="loadOrHideOlder" v-if="!loading2 && !loading">{{
         showingOlder
            ? "Hide older versions" : "Load older versions" }}</button>

      <div v-if="loading2" class="text-xl font-bold animate-pulse">Loading...</div>

      <VersionCard v-for="release in allReleases" :version="release.version" :date="release.date" :url="release.url"
         :windows-setup-url="release.windowsSetupUrl" :macos-setup-url="release.macosSetupUrl"
         :linux-setup-url="release.linuxSetupUrl" />
      <VersionCard v-for="release in allReleases" :version="release.version" :date="release.date" :url="release.url"
         :windows-setup-url="release.windowsSetupUrl" :macos-setup-url="release.macosSetupUrl"
         :linux-setup-url="release.linuxSetupUrl" />
      <VersionCard v-for="release in allReleases" :version="release.version" :date="release.date" :url="release.url"
         :windows-setup-url="release.windowsSetupUrl" :macos-setup-url="release.macosSetupUrl"
         :linux-setup-url="release.linuxSetupUrl" />
      <VersionCard v-for="release in allReleases" :version="release.version" :date="release.date" :url="release.url"
         :windows-setup-url="release.windowsSetupUrl" :macos-setup-url="release.macosSetupUrl"
         :linux-setup-url="release.linuxSetupUrl" />
      <VersionCard v-for="release in allReleases" :version="release.version" :date="release.date" :url="release.url"
         :windows-setup-url="release.windowsSetupUrl" :macos-setup-url="release.macosSetupUrl"
         :linux-setup-url="release.linuxSetupUrl" />

      <div v-if="showingOlder && allReleases.length === 0" class="text-lg">No more releases...</div>
   </div>
</template>

// packages/huginn-website/src/Download.tsx
import type { APIGetAllReleasesResult, APIGetLatestReleaseResult } from "@huginn/shared";

import { useEffect, useState } from "react";

import VersionCard from "./components/VersionCard";

export type FlavourType = "nightly" | "release";

export default function Download() {
   const [latestRelease, setLatestRelease] = useState<APIGetLatestReleaseResult | undefined>(undefined);
   const [allReleases, setAllReleases] = useState<APIGetAllReleasesResult>([]);
   const [loading, setLoading] = useState(false);
   const [loadingOlder, setLoadingOlder] = useState(false);
   const [showingOlder, setShowingOlder] = useState(false);

   useEffect(() => {
      let isActive = true;

      const loadLatest = async () => {
         setLoading(true);
         try {
            const url = new URL("/api/latest-release", import.meta.env.VITE_SERVER_ADDRESS).toString();
            const data = await (await fetch(url)).json();
            if (isActive) {
               setLatestRelease(data);
            }
         } finally {
            if (isActive) {
               setLoading(false);
            }
         }
      };

      loadLatest();

      return () => {
         isActive = false;
      };
   }, []);

   const loadOrHideOlder = async () => {
      if (showingOlder) {
         setAllReleases([]);
         setShowingOlder(false);
         return;
      }

      setLoadingOlder(true);

      const url = new URL("/api/all-releases", import.meta.env.VITE_SERVER_ADDRESS).toString();
      const data = (await (await fetch(url)).json()) as APIGetAllReleasesResult;
      setAllReleases(data.filter((release) => release.version !== latestRelease?.version));

      setLoadingOlder(false);
      setShowingOlder(true);
   };

   return (
      <>
         <div className="mt-32 flex w-full flex-col md:mt-52">
            <div className="mb-10 flex flex-col">
               <div className="w-full text-center text-5xl font-extrabold">Download Huginn</div>
               <div className="mt-7 w-full text-center text-xl">Please choose your version</div>
            </div>
         </div>
         <div className="mb-auto flex flex-col items-center gap-y-5 px-4 pb-32">
            {loading ? <div className="animate-pulse text-xl font-bold">Loading...</div> : null}

            {latestRelease ? (
               <VersionCard
                  version={latestRelease.version}
                  date={latestRelease.date}
                  latest
                  url={latestRelease.url}
                  windowsSetupUrl={latestRelease.windowsSetupUrl}
                  macosSetupUrl={latestRelease.macosSetupUrl}
                  linuxSetupUrl={latestRelease.linuxSetupUrl}
               />
            ) : null}

            {!loadingOlder && !loading ? (
               <button className="text-accent text-lg hover:underline" onClick={loadOrHideOlder} type="button">
                  {showingOlder ? "Hide older versions" : "Load older versions"}
               </button>
            ) : null}

            {loadingOlder ? <div className="animate-pulse text-xl font-bold">Loading...</div> : null}

            {allReleases.map((release) => (
               <VersionCard
                  key={release.version}
                  version={release.version}
                  date={release.date}
                  url={release.url}
                  windowsSetupUrl={release.windowsSetupUrl}
                  macosSetupUrl={release.macosSetupUrl}
                  linuxSetupUrl={release.linuxSetupUrl}
               />
            ))}

            {showingOlder && allReleases.length === 0 ? <div className="text-lg">No more releases...</div> : null}
         </div>
      </>
   );
}
