// packages/huginn-website/src/components/CustomList.vue
<script setup lang="ts">
import { Listbox, ListboxButton, ListboxOption, ListboxOptions } from "@headlessui/vue";
import { Icon } from "@iconify/vue";
import { ref } from "vue";

const optionsProps = defineProps<{
   options: { text: string; icon: string; disabled: boolean; hidden: boolean }[];
   default: string;
}>();

defineOptions({
   inheritAttrs: false,
});

const selectedOption = ref(optionsProps.options.find((x) => x.text.trim().toLowerCase() === optionsProps.default));
</script>

<template>
   <Listbox v-model="selectedOption">
      <div class="relative mx-2 select-none">
         <ListboxButton class="flex items-center rounded-md bg-secondary px-2 py-1" :class="$attrs.class">
            <Icon :icon="selectedOption?.icon ?? 'mdi:cross'" class="mr-1" />
            {{ selectedOption?.text }}
            <Icon icon="gridicons:dropdown" class="ml-auto" />
         </ListboxButton>

         <ListboxOptions
            class="ui-open:bg-secondary ui-open:rounded-md ui-open:shadow-lg absolute mt-1 w-full overflow-hidden">
            <ListboxOption v-for="option in optionsProps.options" :key="option.text" :value="option"
               :disabled="option.disabled"
               @click="!option.disabled && $emit('changed', option.text.trim().toLowerCase())"
               class="ui-disabled:cursor-not-allowed ui-disabled:text-text/50 hover:ui-disabled:bg-black/30 flex cursor-pointer items-center px-2 py-1 pr-9 hover:bg-black/50"
               :class="{ hidden: option.hidden }">
               <Icon :icon="option.icon" class="mr-1" />
               {{ option.text }}
            </ListboxOption>
         </ListboxOptions>
      </div>
   </Listbox>
</template>

// packages/huginn-website/src/components/CustomList.tsx
import { Listbox } from "@headlessui/react";
import { Icon } from "@iconify/react";
import { useMemo, useState } from "react";

type ListOption = {
  text: string;
  icon: string;
  disabled: boolean;
  hidden: boolean;
};

type CustomListProps = {
  options: ListOption[];
  default: string;
  className?: string;
  onChanged?: (value: string) => void;
};

export default function CustomList({
  options,
  default: defaultValue,
  className,
  onChanged,
}: CustomListProps) {
  const initialOption = useMemo(() => {
    return (
      options.find((option) => option.text.trim().toLowerCase() === defaultValue) ??
      options[0] ??
      null
    );
  }, [defaultValue, options]);

  const [selectedOption, setSelectedOption] = useState<ListOption | null>(initialOption);

  return (
    <Listbox
      value={selectedOption}
      onChange={(option) => {
        setSelectedOption(option);
        onChanged?.(option.text.trim().toLowerCase());
      }}
    >
      <div className="relative mx-2 select-none">
        <Listbox.Button
          className={`flex items-center rounded-md bg-secondary px-2 py-1 ${className ?? ""}`.trim()}
        >
          <Icon icon={selectedOption?.icon ?? "mdi:cross"} className="mr-1" />
          {selectedOption?.text}
          <Icon icon="gridicons:dropdown" className="ml-auto" />
        </Listbox.Button>

        <Listbox.Options className="absolute mt-1 w-full overflow-hidden rounded-md bg-secondary shadow-lg">
          {options.map((option) => (
            <Listbox.Option
              key={option.text}
              value={option}
              disabled={option.disabled}
              className={({ active, disabled }) =>
                `flex cursor-pointer items-center px-2 py-1 pr-9 ${
                  active && !disabled ? "bg-black/50" : ""
                } ${disabled ? "cursor-not-allowed text-text/50" : ""} ${option.hidden ? "hidden" : ""}`
              }
            >
              <Icon icon={option.icon} className="mr-1" />
              {option.text}
            </Listbox.Option>
          ))}
        </Listbox.Options>
      </div>
    </Listbox>
  );
}
