// packages/huginn-website/src/components/ThemeChanger.vue
<script setup lang="ts">
import { Icon } from '@iconify/vue/dist/iconify.js';
import { ref } from 'vue';
import { type ColorTheme, ceruleanTheme, charcoalTheme, coffeeTheme, eggplantTheme, pineGreenTheme, useChangeTheme } from '../scripts/useChangeTheme';

const isOpen = ref(false)

function toggleMenu() {
   isOpen.value = !isOpen.value
   console.log(isOpen.value)
}

function chooseTheme(theme: ColorTheme) {
   useChangeTheme(theme.type)
   toggleMenu()
}

</script>

<template>
   <div class="w-fit">
      <button @click="toggleMenu"
         class="rounded-full z-30 p-4 transition-all shadow-md hover:shadow-lg bg-tertiary shadow-4xl ">
         <Icon icon="material-symbols:brush" class="size-7 text-accent" />
      </button>

      <Transition name="menu">
         <div v-if="isOpen"
            class="absolute p-3 gap-x-2 grid grid-cols-2 md:h-36 h-44 md:w-24 w-28 bg-tertiary outline outline-1 outline-primary shadow-2xl rounded-lg right-20 bottom-0">

            <button @click="chooseTheme(coffeeTheme)"
               class="rounded-full flex items-center justify-center bg-black/30 md:size-8 size-10 shrink-0">
               <div class="rounded-full md:size-6 size-8 bg-[#D99A6C]"></div>
            </button>

            <button @click="chooseTheme(ceruleanTheme)"
               class="rounded-full flex items-center justify-center bg-black/30 md:size-8 size-10 shrink-0">
               <div class="rounded-full md:size-6 size-8 bg-[#00A7E3]"></div>
            </button>

            <button @click="chooseTheme(pineGreenTheme)"
               class="rounded-full flex items-center justify-center bg-black/30 md:size-8 size-10 shrink-0">
               <div class="rounded-full md:size-6 size-8 bg-[#02CAB9]"></div>
            </button>

            <button @click="chooseTheme(eggplantTheme)"
               class="rounded-full flex items-center justify-center bg-black/30 md:size-8 size-10 shrink-0">
               <div class="rounded-full md:size-6 size-8 bg-[#DC8B9A]"></div>
            </button>

            <button @click="chooseTheme(charcoalTheme)"
               class="rounded-full flex items-center justify-center bg-black/30 md:size-8 size-10 shrink-0">
               <div class="rounded-full md:size-6 size-8 bg-[#9FB1BD]"></div>
            </button>
         </div>
      </Transition>
   </div>

</template>

<style>
.menu-enter-from,
.menu-leave-to {
   opacity: 0;
   transform: scale(0.9);
}

.menu-enter-active,
.menu-leave-active {
   transition-property: all;
   transition-duration: 250ms;
   transition-timing-function: ease;
}
</style>

// packages/huginn-website/src/components/ThemeChanger.tsx
import { Icon } from "@iconify/react";
import { useState } from "react";

import { ceruleanTheme, charcoalTheme, coffeeTheme, eggplantTheme, pineGreenTheme, type ColorTheme, useTheme } from "../scripts/useChangeTheme";

type ThemeChangerProps = {
   className?: string;
};

export default function ThemeChanger({ className }: ThemeChangerProps) {
   const [isOpen, setIsOpen] = useState(false);
   const { setThemeType } = useTheme();

   const toggleMenu = () => {
      setIsOpen((prev) => !prev);
   };

   const chooseTheme = (theme: ColorTheme) => {
      setThemeType(theme.type);
      setIsOpen(false);
   };

   const rootClassName = ["w-fit", className].filter(Boolean).join(" ");

   return (
      <div className={rootClassName}>
         <button onClick={toggleMenu} className="shadow-4xl bg-tertiary z-30 rounded-full p-4 shadow-md transition-all hover:shadow-lg" type="button">
            <Icon icon="material-symbols:brush" className="text-accent size-7" />
         </button>

         <div
            className={`bg-tertiary outline-primary ease absolute right-20 bottom-0 grid h-44 w-28 grid-cols-2 gap-x-2 rounded-lg p-3 shadow-2xl outline outline-1 transition-all duration-[250ms] md:h-36 md:w-24 ${
               isOpen ? "scale-100 opacity-100" : "pointer-events-none scale-90 opacity-0"
            }`}
         >
            <button
               onClick={() => chooseTheme(coffeeTheme)}
               className="flex size-10 shrink-0 items-center justify-center rounded-full bg-black/30 md:size-8"
               type="button"
            >
               <div className="size-8 rounded-full bg-[#D99A6C] md:size-6"></div>
            </button>

            <button
               onClick={() => chooseTheme(ceruleanTheme)}
               className="flex size-10 shrink-0 items-center justify-center rounded-full bg-black/30 md:size-8"
               type="button"
            >
               <div className="size-8 rounded-full bg-[#00A7E3] md:size-6"></div>
            </button>

            <button
               onClick={() => chooseTheme(pineGreenTheme)}
               className="flex size-10 shrink-0 items-center justify-center rounded-full bg-black/30 md:size-8"
               type="button"
            >
               <div className="size-8 rounded-full bg-[#02CAB9] md:size-6"></div>
            </button>

            <button
               onClick={() => chooseTheme(eggplantTheme)}
               className="flex size-10 shrink-0 items-center justify-center rounded-full bg-black/30 md:size-8"
               type="button"
            >
               <div className="size-8 rounded-full bg-[#DC8B9A] md:size-6"></div>
            </button>

            <button
               onClick={() => chooseTheme(charcoalTheme)}
               className="flex size-10 shrink-0 items-center justify-center rounded-full bg-black/30 md:size-8"
               type="button"
            >
               <div className="size-8 rounded-full bg-[#9FB1BD] md:size-6"></div>
            </button>
         </div>
      </div>
   );
}
